### ISSUE TITLE
More playback control

### ISSUE THREAD

**Issue by gabrielibagon** [OpenBCI/OpenBCI_GUI_v2.0#2]
A feature request is extended playback control, such as the ability to start the file from the beginning while still in the GUI, viewing data. When playing back files, I would often want to start at the beginning to re-examine the data I've seen so far; however, the GUI currently only allows for pause ("Stop data stream") and resume ("Start data stream"). The only way to start from the beginning is to exit the system and then restart the system. It would be great to have a "Reset"/"Start from beginning" option in data view mode. 

Other options could be "jump back 5 seconds" to re-examine particular moments in the playback. Or set a marker to be able to start from (e.g. play back the data from timepoint 1:30).

**Comment by aj-ptw** [comment]
close see #38
