### ISSUE TITLE
splitLineCSV throws error

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_GUI_v2.0#22]
Trying to run master and getting this error...

![screen shot 2016-08-10 at 1 36 25 pm](https://cloud.githubusercontent.com/assets/11437469/17563917/85a275da-5eff-11e6-9bb1-d1e64b81364f.png)

**Comment by pushtheworldllc** [comment]
This is because of a bug with processing 3.1.2, do not update!

**Comment by pushtheworldllc** [comment]
From the processing guys, we should never have used `splitLineCSV()` and functions like these are subject to change in minor updates to processing!! See this issue here! https://github.com/processing/processing/issues/4611

**Comment by cfausn** [comment]
I've found that passing the buffer to splitLineCSV() fixes this bug with newer processing. Simply change it to splitLineCSV(line, reader)

**Comment by aj-ptw** [comment]
I disagree. `splitLineCSV` is a protected function and should not be used in the application.

**Comment by cfausn** [comment]
haha interesting. For the newest version of processing though it doesn't let you compile without passing in the reader, dunno why.

**Comment by aj-ptw** [comment]
They changed the interface for that function from one arg to two args... see #25 PR for a fix https://github.com/aj-ptw/OpenBCI_GUI_v2.0/commit/53776fddab94a02700cbcc1cd8dc9e107bd7e33b#diff-5fbebc9acb054941aa8e1303d08be960R241
