### ISSUE TITLE
OpenBCI_GUI Freezes on macOS Sierra with LIVE Data Source

### ISSUE THREAD

**Issue by valencra** [OpenBCI/OpenBCI_GUI_v2.0#29]
I just received my OpenBCI 32-bit board, and, when I ran it with the GUI, it just freezes instead of establishing a connection:

![image](https://cloud.githubusercontent.com/assets/9492937/19210470/04c24a96-8cf2-11e6-9e1a-55659babb35a.png)

After waiting for a while, it becomes a blank screen:

![image](https://cloud.githubusercontent.com/assets/9492937/19210480/383d1f7c-8cf2-11e6-831f-6ac1b6cf955a.png)

**Comment by aj-ptw** [comment]
You hit start and just nothing? Is there any print outs you see on the bottom of the window? Have you tried the older version one build that can be downloaded from the website.

**Comment by valencra** [comment]
Yes after making all the required selections and pressing start system it freezes. In the tutorial it says that the bottom status should change to “Initializing communication w/ your OpenBCI board”, but that does not happen. If I wait 5 seconds, which is the amount of time indicated in the tutorial, nothing happens and the screen becomes blank. If I try to maximize the window, it completely exits the program.

**Comment by aj-ptw** [comment]
Could be. Maybe try downloading the repo for the GUI and run it from processing.

**Comment by valencra** [comment]
I tried downloading the repo and running it from processing, and it still has the same problem:
![screenshot 2016-10-08 21 01 24](https://cloud.githubusercontent.com/assets/9492937/19216848/c92fedc2-8d9a-11e6-9a58-5f3ba5abd020.png)

The snapshot does not show it, but there's just a spinner that never goes away

**Comment by aj-ptw** [comment]
Does synthetic work?

**Comment by valencra** [comment]
On the standalone app, yes:
![screenshot 2016-10-08 21 07 54](https://cloud.githubusercontent.com/assets/9492937/19216860/4e2ef00e-8d9b-11e6-8aa1-66250e7687fd.png)

When run with processing, it freezes as well:
![screenshot 2016-10-08 21 09 42](https://cloud.githubusercontent.com/assets/9492937/19216864/8c9c495e-8d9b-11e6-8afb-fae0a239b325.png)

**Comment by aj-ptw** [comment]
Closing for now

**Comment by valencra** [comment]
Oh is there no possible solution to the problem? Please let me know if you plan on opening it once again in the future.

**Comment by aj-ptw** [comment]
I closed because this is still alpha and there is a big chance your issue was/will be solved by the time this is released by it go live in december

**Comment by valencra** [comment]
I see. Thank you for letting me know, AJ.
