### ISSUE TITLE
Widget: EMG

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_GUI_v2.0#40]
- [X] Backend
- [X] Sliders
- [ ] Stop circles from leaving window
- [ ] Fix config window
- [ ] Clean up and finalize

**Comment by aj-ptw** [comment]
Is this done with #63?

**Comment by cfausn** [comment]
@aj-ptw how does this differ from #52?

**Comment by aj-ptw** [comment]
This pr, #40, is complete when you have finalized the backend of the EMG widget. Then @sunwangshu was supposed to finish the frontend that you said you were spending a lot of time on yesterday.

**Comment by cfausn** [comment]
Gotcha. Backend is completely finished, I'm working on frontend right now and @sunwangshu is going to focus her efforts on the accelerometer widget.

**Comment by aj-ptw** [comment]
ok that's cool. let's close this issue then and assign #52 to you!
