### ISSUE TITLE
Widget: EMG Responsiveness

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_GUI_v2.0#52]
Improve the overall responsiveness of the EMG widget

- [X] Backend
- [X] Sliders
- [x] Stop circles from leaving window
- [x] Fix config window

**Comment by aj-ptw** [comment]
@cfausn did #63 close this?

**Comment by cfausn** [comment]
No I've still got some work to do, mostly just the config window. Once that's done this should be good to go. Just wanted to get the OpenBionics widget on the dev repo

**Comment by aj-ptw** [comment]
ok awesome!

**Comment by cfausn** [comment]
Never mind didn't realize this was just backend, backend is complete for the EMG widget.

**Comment by cfausn** [comment]
This can be closed!
